Repository epam/edp-cluster-add-ons, pull requests merged in 2024-09, with the labels that each got.

#135 chore: Migrate from KeycloakRealmRoleBatch to KeycloakRealmRole (#134)
  add-ons/extensions-oidc/templates/shared/realmrole-administrator.yaml
  add-ons/extensions-oidc/templates/shared/realmrole-developer.yaml
  add-ons/extensions-oidc/templates/shared/realmrolebatch.yaml
  add-ons/sonar/templates/oidc/realmrole-administrator.yaml
  add-ons/sonar/templates/oidc/realmrole-developer.yaml
Labels: enhancement, routine

#137 chore: Move Role-ARN Annotation from Service Account to Values (#136)
  add-ons/argo-cd/README.md
  add-ons/argo-cd/templates/external-secrets/serviceaccount.yaml
  add-ons/argo-cd/values.yaml
  add-ons/awx-operator/README.md
  add-ons/awx-operator/templates/external-secrets/serviceaccount.yaml
  add-ons/awx-operator/values.yaml
  add-ons/defectdojo/README.md
  add-ons/defectdojo/templates/external-secrets/serviceaccount.yaml
  add-ons/defectdojo/values.yaml
  add-ons/fluent-bit/README.md
  add-ons/fluent-bit/templates/external-secrets/serviceaccount.yaml
  add-ons/fluent-bit/values.yaml
  add-ons/harbor-ha-okd/README.md
  add-ons/harbor-ha-okd/templates/external-secrets/serviceaccount.yaml
  add-ons/harbor-ha-okd/values.yaml
  add-ons/harbor-ha/README.md
  add-ons/harbor-ha/templates/external-secrets/serviceaccount.yaml
  add-ons/harbor-ha/values.yaml
  add-ons/harbor/README.md
  add-ons/harbor/templates/external-secrets/serviceaccount.yaml
  add-ons/harbor/values.yaml
  add-ons/keycloak-postgresql/README.md
  add-ons/keycloak-postgresql/templates/external-secrets/serviceaccount.yaml
  add-ons/keycloak-postgresql/values.yaml
  add-ons/keycloak/README.md
  add-ons/keycloak/templates/external-secrets/serviceaccount.yaml
  add-ons/keycloak/values.yaml
  add-ons/kibana/templates/external-secrets/serviceaccount.yaml
  add-ons/kibana/values.yaml
  add-ons/nexus-operator/README.md
  add-ons/nexus-operator/templates/external-secret/serviceaccount.yaml
  add-ons/nexus-operator/values.yaml
  add-ons/nexus/README.md
  add-ons/nexus/templates/external-secrets/serviceaccount.yaml
  add-ons/nexus/values.yaml
  add-ons/opensearch/README.md
  add-ons/opensearch/templates/external-secrets/serviceaccount.yaml
  add-ons/opensearch/values.yaml
  add-ons/prometheus-operator/README.md
  add-ons/prometheus-operator/templates/external-secrets/serviceaccount.yaml
  add-ons/prometheus-operator/values.yaml
  add-ons/report-portal/README.md
  add-ons/report-portal/templates/external-secrets/serviceaccount.yaml
  add-ons/report-portal/values.yaml
  add-ons/sonar-operator/README.md
  add-ons/sonar-operator/templates/external-secrets/serviceaccount.yaml
  add-ons/sonar-operator/values.yaml
  add-ons/vault-kms/README.md
  add-ons/vault-kms/templates/external-secrets/serviceaccount.yaml
  add-ons/vault-kms/values.yaml
  add-ons/vault-okd/README.md
  add-ons/vault-okd/templates/external-secrets/serviceaccount.yaml
  add-ons/vault-okd/values.yaml
Labels: enhancement

#133 chore: Update extensions-oidc application (#129)
  add-ons/extensions-oidc/Chart.yaml
  add-ons/extensions-oidc/README.md
  add-ons/extensions-oidc/templates/_helpers.tpl
  add-ons/extensions-oidc/templates/broker/keycloak-client-shared.yaml
  add-ons/extensions-oidc/templates/broker/keycloak-realm.yaml
  add-ons/extensions-oidc/templates/external-secrets/externalsecret-keycloak-client-shared-secret.yaml
  add-ons/extensions-oidc/templates/external-secrets/keycloak-client-eks-secret.yaml
  add-ons/extensions-oidc/templates/keycloak.yaml
  add-ons/extensions-oidc/templates/kubernetes/clusterrolebinding-admin.yaml
  add-ons/extensions-oidc/templates/kubernetes/keycloak-client.yaml
  add-ons/extensions-oidc/templates/kubernetes/keycloak-clientscope.yaml
  add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-admins.yaml
  add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-builders.yaml
  add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-cluster-admins.yaml
  add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-deployers.yaml
  add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-developers.yaml
  add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-viewers.yaml
  add-ons/extensions-oidc/templates/shared/keycloak-realm.yaml
  add-ons/extensions-oidc/templates/shared/shared-idp.yaml
  add-ons/extensions-oidc/values.yaml
  add-ons/keycloak-operator/Chart.yaml
  add-ons/keycloak-operator/README.md
  add-ons/keycloak-operator/values.yaml
  chart/templates/extensions-oidc.yaml
Labels: bug, component-update, routine

#132 chore: Add oauth2-proxy (#131)
  add-ons/oauth2-proxy/Chart.yaml
  add-ons/oauth2-proxy/README.md
  add-ons/oauth2-proxy/templates/external-secrets/oauth2-proxy.yaml
  add-ons/oauth2-proxy/templates/external-secrets/secretstore-aws.yaml
  add-ons/oauth2-proxy/templates/external-secrets/secretstore-generic.yaml
  add-ons/oauth2-proxy/templates/external-secrets/serviceaccount.yaml
  add-ons/oauth2-proxy/templates/keycloak/clientscope-oauth2-proxy.yaml
  add-ons/oauth2-proxy/templates/keycloak/keycloakclient-oauth2-proxy.yaml
  add-ons/oauth2-proxy/values.yaml
  chart/README.md
  chart/templates/oauth2-proxy.yaml
  chart/values.yaml
Labels: enhancement
