Repository epam/edp-cluster-add-ons, pull requests merged in 2024-10, with the labels that each got.

#142 chore: Align Widgets Users Permissions Across KRCI Platform
  add-ons/sonar-operator/templates/external-secrets/externalsecret-sonar-view-password-secret.yaml
  add-ons/sonar-operator/templates/sonar/permission_template.yaml
  add-ons/sonar-operator/templates/sonar/user_view.yaml
Labels: enhancement

#144 chore: Bump nexus version
  README.md
  add-ons/nexus/Chart.yaml
  add-ons/nexus/README.md
  add-ons/nexus/values.yaml
Labels: component-update

#146 chore: Bump PGO version from 5.4.3 to 5.7.0(#145)
  README.md
  add-ons/postgres-operator/Chart.yaml
  add-ons/postgres-operator/README.md
  add-ons/postgres-operator/values.yaml
Labels: enhancement

#147 chore: Update Pull Request Template (#24)
  pull_request_template.md
Labels: enhancement

#149 chore: Add krakend(#148)
  README.md
  add-ons/krakend/Chart.yaml
  add-ons/krakend/README.md
  add-ons/krakend/templates/external-secrets/krakend.yaml
  add-ons/krakend/templates/external-secrets/secretstore-aws.yaml
  add-ons/krakend/templates/external-secrets/secretstore-generic.yaml
  add-ons/krakend/templates/external-secrets/serviceaccount.yaml
  add-ons/krakend/values.yaml
  chart/README.md
  chart/templates/krakend.yaml
  chart/values.yaml
Labels: feature

#150 fix: Make argocd project a configurable value for karend(#148)
  chart/templates/krakend.yaml
Labels: bug

#151 fix: Update cluster role name
  add-ons/kuberocketci-rbac/templates/kubernetes/clusterrolebinding-admin.yaml
Labels: bug

#152 chore: Remove unused group in sonar
  add-ons/sonar-operator/templates/sonar/group_edp.yaml
Labels: routine

#153 fix: Update rbac model for sonar
  add-ons/sonar-operator/templates/sonar/user_ci.yaml
  add-ons/sonar-operator/templates/sonar/view_group.yaml
Labels: bug

#154 fix: Parameterize argocd url into oidc template
  add-ons/argo-cd/templates/oidc/keycloak-client.yaml
Labels: bug
