Repository epam/edp-cluster-add-ons, pull requests merged in 2024-12, with the labels that each got.

#180 feat: Implement KrakenD integration with OpenSearch (#179)
  clusters/core/addons/krakend/README.md
  clusters/core/addons/krakend/values.yaml
Labels: feature

#188 chore: Upgrade Sonar Plugins to Latest Stable Versions
  clusters/core/addons/sonar/README.md
  clusters/core/addons/sonar/values.yaml
Labels: enhancement

#191 chore: Update KrakenD chart version to 0.1.36 (#190)
  clusters/core/addons/krakend/Chart.yaml
  clusters/core/addons/krakend/README.md
  clusters/core/addons/krakend/values.yaml
Labels: enhancement

#194 fix: Fix typo in add-ons
  argo-cd/templates/external-secrets/serviceaccount.yaml
  clusters/core/apps/templates/cert-manager.yaml
  clusters/core/bootstrap-addons.yaml
Labels: bug, routine

#195 chore: Update KrakenD README.md template (#185)
  clusters/core/addons/krakend/README.md
  clusters/core/addons/krakend/README.md.gotmpl
Labels: enhancement

#198 chore: Update Naming Convention for Nexus-Operator Resources
  clusters/core/addons/nexus-operator/Chart.yaml
  clusters/core/addons/nexus-operator/templates/nexus/ci-nexus.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/container/krci-container-blobstore.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/container/krci-container-hosted.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/dotnet/krci-dotnet-blobstore.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/dotnet/krci-dotnet-cleanup-policy.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/dotnet/krci-dotnet-group.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/dotnet/krci-dotnet-hosted.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/dotnet/krci-dotnet-proxy.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/dotnet/krci-dotnet-releases.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/dotnet/krci-dotnet-script.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/dotnet/krci-dotnet-snapshots.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/maven/krci-maven-blobstore.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/maven/krci-maven-cleanup-policy.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/maven/krci-maven-group.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/maven/krci-maven-proxy.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/maven/krci-maven-releases.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/maven/krci-maven-snapshots.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/npm/krci-npm-blobstore.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/npm/krci-npm-cleanup-policy.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/npm/krci-npm-group.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/npm/krci-npm-hosted.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/npm/krci-npm-proxy.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/npm/krci-npm-releases.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/npm/krci-npm-snapshots.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/python/krci-python-blobstore.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/python/krci-python-cleanup-policy.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/python/krci-python-group.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/python/krci-python-proxy.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/python/krci-python-releases.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/python/krci-python-snapshots.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/yum/krci-yum-blobstore.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/yum/krci-yum-proxy.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/yum/krci-yum-releases.yaml
  clusters/core/addons/nexus-operator/templates/nexus/repository/yum/krci-yum-snapshots.yaml
  clusters/core/addons/nexus-operator/templates/nexus/role-edp-admin.yaml
  clusters/core/addons/nexus-operator/templates/nexus/role-edp-viewer.yaml
  clusters/core/addons/nexus-operator/templates/scripts/create-tasks.yaml
Labels: enhancement

#197 chore: Update Argo CD to v7.7.10 (#196)
  README.md
  argo-cd/Chart.yaml
  argo-cd/README.md
  clusters/core/addons/argo-cd/Chart.yaml
  clusters/core/addons/argo-cd/README.md
Labels: enhancement

#199 chore: Update ArgoCD RBAC to avoid exec error
  clusters/core/addons/argo-cd/README.md
  clusters/core/addons/argo-cd/templates/appProject.yaml
  clusters/core/addons/argo-cd/values.yaml
Labels: enhancement

#201 chore: Add Tekton Custom Task integration (#200)
  README.md
  clusters/core/addons/tekton-custom-task/Chart.yaml
  clusters/core/addons/tekton-custom-task/README.md
  clusters/core/addons/tekton-custom-task/values.yaml
  clusters/core/apps/README.md
  clusters/core/apps/templates/tekton-custom-task.yaml
  clusters/core/apps/values.yaml
Labels: enhancement
