Repository epam/edp-cluster-add-ons, pull requests merged in 2025-09, with the labels that each got.

#343 chore: Update pgadmin4 chart version
  README.md
  clusters/core/addons/pgadmin/Chart.yaml
  clusters/core/addons/pgadmin/README.md
Labels: enhancement

#358 chore: Bump open-telemetry operator version(#357)
  README.md
  clusters/core/addons/minio-operator/README.md
  clusters/core/addons/opentelemetry-operator/Chart.yaml
  clusters/core/addons/opentelemetry-operator/README.md
  clusters/core/addons/opentelemetry-operator/templates/opentelementrycollector.yaml
Labels: enhancement

#356 chore: Bump Vault to 1.20.1
  clusters/core/addons/vault-kms/Chart.yaml
  clusters/core/addons/vault-kms/README.md
  clusters/core/addons/vault-okd/Chart.yaml
  clusters/core/addons/vault-okd/README.md
  clusters/core/addons/vault-operator/Chart.yaml
  clusters/core/addons/vault-operator/README.md
  clusters/core/addons/vault/Chart.yaml
  clusters/core/addons/vault/README.md
Labels: dependencies

#361 chore: Migrate images bitnami to bitnamilegacy(#360)
  clusters/core/addons/awx-operator/templates/init-job/init-job.yaml
  clusters/core/addons/nexus-ce/values.yaml
  clusters/core/addons/report-portal/templates/init-job/init-job.yaml
Labels: enhancement

#363 chore: Update Karpenter role name
  clusters/core/addons/karpenter-np/templates/node-class.yaml
  clusters/core/addons/karpenter/README.md
  clusters/core/addons/karpenter/values.yaml
Labels: enhancement, dependencies
