Repository epam/edp-cluster-add-ons, pull requests merged in 2025-08, with the labels that each got.

#318 chore: Update Karpenter version
  README.md
  clusters/core/addons/karpenter/Chart.yaml
  clusters/core/addons/karpenter/README.md
Labels: enhancement

#314 chore: Bump sonarqube version
  clusters/core/addons/sonar/Chart.yaml
  clusters/core/addons/sonar/README.md
  clusters/core/addons/sonar/values.yaml
Labels: enhancement, feature, dependencies

#322 chore: Bump ArgoCD version to 8.2.5(#321)
  README.md
  argo-cd/Chart.yaml
  argo-cd/README.md
  argo-cd/values.yaml
  clusters/core/addons/argo-cd/Chart.yaml
  clusters/core/addons/argo-cd/README.md
  clusters/core/addons/argo-cd/values.yaml
Labels: enhancement

#329 chore: Update capsule to 0.7.4
  clusters/core/addons/capsule/Chart.yaml
  clusters/core/addons/capsule/README.md
Labels: enhancement, dependencies

#335 chore: Bump PGO version to 5.8.2(#807)
  README.md
  clusters/core/addons/postgres-operator/Chart.yaml
  clusters/core/addons/postgres-operator/README.md
  clusters/core/addons/postgres-operator/values.yaml
Labels: enhancement
