Repository epam/edp-cluster-add-ons, pull requests merged in 2025-02, with the labels that each got.

#215 chore: Bump defectdojo to 2.42.1 replace RabbitMQ with Redis(#213)
  clusters/core/addons/defectdojo/Chart.yaml
  clusters/core/addons/defectdojo/README.md
  clusters/core/addons/defectdojo/README.md.gotmpl
  clusters/core/addons/defectdojo/templates/external-secrets/externalsecret-defectdojo-redis-specific.yaml
  clusters/core/addons/defectdojo/templates/postgresql.yaml
  clusters/core/addons/defectdojo/values.yaml
Labels: enhancement

#227 chore: Align ExternalSecret name pattern(#213)
  clusters/core/addons/argo-cd/templates/external-secrets/externalsecret-argocd-vcs.yaml
  clusters/core/addons/argo-cd/templates/external-secrets/keycloak-client-argocd-secret.yaml
  clusters/core/addons/argo-cd/values.yaml
  clusters/core/addons/atlantis/values.yaml
  clusters/core/addons/defectdojo/templates/external-secrets/defectdojo-extrasecrets.yaml
  clusters/core/addons/defectdojo/templates/external-secrets/defectdojo-redis-specific.yaml
  clusters/core/addons/defectdojo/templates/external-secrets/defectdojo.yaml
  clusters/core/addons/defectdojo/templates/external-secrets/keycloak-client-defectdojo-secret.yaml
  clusters/core/addons/fluent-bit/templates/external-secrets/fluentbit-creds.yaml
  clusters/core/addons/harbor-ha-okd/templates/external-secrets/centralized-minio-users.yaml
  clusters/core/addons/harbor-ha-okd/templates/external-secrets/harbor-s3.yaml
  clusters/core/addons/harbor-ha-okd/templates/external-secrets/harbor.yaml
  clusters/core/addons/harbor-ha-okd/templates/external-secrets/keycloak-client-harbor-secret.yaml
  clusters/core/addons/harbor-ha-okd/templates/external-secrets/minio-admin-ui.yaml
  clusters/core/addons/harbor-ha-okd/templates/external-secrets/redis-creds.yaml
  clusters/core/addons/harbor-ha/templates/external-secrets/centralized-minio-users.yaml
  clusters/core/addons/harbor-ha/templates/external-secrets/harbor-s3.yaml
  clusters/core/addons/harbor-ha/templates/external-secrets/harbor.yaml
  clusters/core/addons/harbor-ha/templates/external-secrets/keycloak-client-harbor-secret.yaml
  clusters/core/addons/harbor-ha/templates/external-secrets/minio-admin-ui.yaml
  clusters/core/addons/harbor-ha/templates/external-secrets/redis-creds.yaml
  clusters/core/addons/harbor/templates/external-secrets/harbor.yaml
  clusters/core/addons/harbor/templates/external-secrets/keycloak-client-harbor-secret.yaml
  clusters/core/addons/keycloak-postgresql/templates/external-secrets/keycloak-postgresql.yaml
  clusters/core/addons/keycloak/templates/external-secrets/keycloak-admin-creds.yaml
  clusters/core/addons/kibana/templates/external-secrets/keycloak-client-kibana-secret.yaml
  clusters/core/addons/kuberocketci-rbac/templates/external-secrets/keycloak-client-shared-secret.yaml
  clusters/core/addons/kuberocketci-rbac/templates/external-secrets/keycloak.yaml
  clusters/core/addons/nexus-operator/templates/external-secret/nexus-admin-password.yaml
  clusters/core/addons/nexus/templates/external-secrets/keycloak-client-nexus-secret.yaml
  clusters/core/addons/nexus/templates/external-secrets/oauth2-proxy.yaml
  clusters/core/addons/opensearch/templates/external-secrets/fluentbit-creds.yaml
  clusters/core/addons/opensearch/templates/external-secrets/keycloak-client-opensearch-secret.yaml
  clusters/core/addons/opensearch/templates/external-secrets/opensearch-admin-creds.yaml
  clusters/core/addons/opensearch/templates/external-secrets/opensearch-dashboards-account.yaml
  clusters/core/addons/prometheus-operator/templates/external-secrets/grafana-admin-creds.yaml
  clusters/core/addons/prometheus-operator/templates/external-secrets/keycloak-client-grafana-secret.yaml
  clusters/core/addons/report-portal/templates/external-secrets/keycloak-client-report-portal-secret.yaml
  clusters/core/addons/report-portal/templates/external-secrets/reportportal-minio-creds.yaml
  clusters/core/addons/report-portal/templates/external-secrets/reportportal-postgresql-creds.yaml
  clusters/core/addons/report-portal/templates/external-secrets/reportportal-rabbitmq-creds.yaml
  clusters/core/addons/sonar-operator/templates/external-secrets/sonar-admin-password.yaml
  clusters/core/addons/vault-kms/templates/external-secrets/keycloak-client-vault-secret.yaml
  clusters/core/addons/vault-okd/templates/external-secrets/keycloak-client-vault-secret.yaml
Labels: enhancement

#230 chore: Align Application namespace creation and readme script(#213)
  README.md
  clusters/core/apps/README.md
  clusters/core/apps/templates/argo-cd.yaml
  clusters/core/apps/templates/atlantis.yaml
  clusters/core/apps/templates/aws-efs-csi-driver.yaml
  clusters/core/apps/templates/awx-operator.yaml
  clusters/core/apps/templates/capsule-tenant.yaml
  clusters/core/apps/templates/capsule.yaml
  clusters/core/apps/templates/cert-manager.yaml
  clusters/core/apps/templates/defectdojo.yaml
  clusters/core/apps/templates/dependency-track.yaml
  clusters/core/apps/templates/external-secrets.yaml
  clusters/core/apps/templates/fluent-bit.yaml
  clusters/core/apps/templates/harbor-ha-okd.yaml
  clusters/core/apps/templates/harbor-ha.yaml
  clusters/core/apps/templates/harbor.yaml
  clusters/core/apps/templates/ingress-nginx-external.yaml
  clusters/core/apps/templates/ingress-nginx.yaml
  clusters/core/apps/templates/jaeger-operator.yaml
  clusters/core/apps/templates/karma-dashboard.yaml
  clusters/core/apps/templates/karpenter-np.yaml
  clusters/core/apps/templates/karpenter.yaml
  clusters/core/apps/templates/keda-tenants.yaml
  clusters/core/apps/templates/keda.yaml
  clusters/core/apps/templates/keycloak-operator.yaml
  clusters/core/apps/templates/keycloak-postgresql.yaml
  clusters/core/apps/templates/keycloak.yaml
  clusters/core/apps/templates/krakend.yaml
  clusters/core/apps/templates/kuberocketci-rbac.yaml
  clusters/core/apps/templates/kuberocketci.yaml
  clusters/core/apps/templates/minio-operator.yaml
  clusters/core/apps/templates/nexus-operator.yaml
  clusters/core/apps/templates/nexus.yaml
  clusters/core/apps/templates/oauth2-proxy.yaml
  clusters/core/apps/templates/opensearch.yaml
  clusters/core/apps/templates/opentelemetry-operator.yaml
  clusters/core/apps/templates/postgres-operator.yaml
  clusters/core/apps/templates/prometheus-operator.yaml
  clusters/core/apps/templates/redis-operator.yaml
  clusters/core/apps/templates/report-portal.yaml
  clusters/core/apps/templates/sonar-operator.yaml
  clusters/core/apps/templates/sonar.yaml
  clusters/core/apps/templates/tekton-cache.yaml
  clusters/core/apps/templates/tekton-custom-task.yaml
  clusters/core/apps/templates/tekton.yaml
  clusters/core/apps/templates/vault-kms.yaml
  clusters/core/apps/templates/vault-okd.yaml
  clusters/core/apps/templates/vault.yaml
  clusters/core/apps/values.yaml
  hack/update_readme.py
Labels: documentation, enhancement

#229 chore: Add instructions for managing ArgoCD VCS secrets(#213)
  argo-cd/README.md
  argo-cd/README.md.gotmpl
Labels: documentation

#228 chore: Add post-install Helm hooks with delete policy(#213)
  argo-cd/templates/appProjectCore.yaml
  argo-cd/templates/appProjectKRCI.yaml
Labels: enhancement

#244 chore: Enable Prefix for KRCI Dependent Tools
  clusters/core/apps/README.md
  clusters/core/apps/values.yaml
Labels: enhancement
