Repository epam/edp-cluster-add-ons, pull requests merged in 2025-01, with the labels that each got.

#204 chore: Bump Tekton components versions (#203)
  clusters/core/addons/tekton/chains.yaml
  clusters/core/addons/tekton/interceptors.yaml
  clusters/core/addons/tekton/pipelines.yaml
  clusters/core/addons/tekton/triggers.yaml
Labels: enhancement

#206 fix: Align metrics parameter in nginx ingress
  clusters/core/addons/ingress-nginx/README.md
  clusters/core/addons/ingress-nginx/values.yaml
Labels: bug

#208 chore: Enable volume expansion for StorageClasses (#207)
  clusters/core/addons/storage-class/storageClass.yaml
  clusters/core/addons/storage-class/storageclass-gp3.yaml
Labels: enhancement

#212 feat: Add autoscaler for KRCI platform
  clusters/core/addons/karpenter-np/Chart.yaml
  clusters/core/addons/karpenter-np/README.md
  clusters/core/addons/karpenter-np/templates/cronjob.yaml
  clusters/core/addons/karpenter-np/templates/node-class.yaml
  clusters/core/addons/karpenter-np/templates/nodepool-cm.yaml
  clusters/core/addons/karpenter-np/templates/nodepool.yaml
  clusters/core/addons/karpenter-np/templates/rbac.yaml
  clusters/core/addons/karpenter-np/values.yaml
  clusters/core/addons/karpenter/Chart.yaml
  clusters/core/addons/karpenter/README.md
  clusters/core/addons/karpenter/values.yaml
  clusters/core/addons/keda-tenants/Chart.yaml
  clusters/core/addons/keda-tenants/README.md
  clusters/core/addons/keda-tenants/README.md.gotmpl
  clusters/core/addons/keda-tenants/templates/cd-pipeline-operator.yaml
  clusters/core/addons/keda-tenants/templates/codebase-operator.yaml
  clusters/core/addons/keda-tenants/templates/git-providers.yaml
  clusters/core/addons/keda-tenants/templates/portal.yaml
  clusters/core/addons/keda-tenants/templates/tekton-interceptor.yaml
  clusters/core/addons/keda-tenants/values.yaml
  clusters/core/addons/keda/Chart.yaml
  clusters/core/addons/keda/README.md
  clusters/core/addons/keda/values.yaml
  clusters/core/apps/README.md
  clusters/core/apps/templates/karpenter-np.yaml
  clusters/core/apps/templates/karpenter.yaml
  clusters/core/apps/templates/keda-tenants.yaml
  clusters/core/apps/templates/keda.yaml
  clusters/core/apps/values.yaml
Labels: enhancement, feature

#210 chore: Migrate Tekton Dashboard to cluster add-ons repo (#209)
  README.md
  clusters/core/addons/tekton-dashboard/Chart.yaml
  clusters/core/addons/tekton-dashboard/README.md
  clusters/core/addons/tekton-dashboard/templates/_helpers.tpl
  clusters/core/addons/tekton-dashboard/templates/cm-dashboard.yaml
  clusters/core/addons/tekton-dashboard/templates/deployment.yaml
  clusters/core/addons/tekton-dashboard/templates/ingress.yaml
  clusters/core/addons/tekton-dashboard/templates/quicklink.yaml
  clusters/core/addons/tekton-dashboard/templates/role-binding.yaml
  clusters/core/addons/tekton-dashboard/templates/role.yaml
  clusters/core/addons/tekton-dashboard/templates/route.yaml
  clusters/core/addons/tekton-dashboard/templates/service-account.yaml
  clusters/core/addons/tekton-dashboard/templates/service.yaml
  clusters/core/addons/tekton-dashboard/values.yaml
  clusters/core/apps/README.md
  clusters/core/apps/templates/tekton-dashboard.yaml
  clusters/core/apps/values.yaml
Labels: enhancement

#214 chore: Align SonarQube ingress values(#213)
  clusters/core/addons/sonar/Chart.yaml
  clusters/core/addons/sonar/README.md
  clusters/core/addons/sonar/values.yaml
Labels: enhancement

#216 chore: Bump DepTrack to 4.12.2 align PGO values(#213)
  README.md
  clusters/core/addons/dependency-track/Chart.yaml
  clusters/core/addons/dependency-track/README.md
  clusters/core/addons/dependency-track/templates/postgres.yaml
  clusters/core/addons/dependency-track/values.yaml
Labels: enhancement

#218 chore: Add readme how manage users in keycloak with krci rbac(#217)
  clusters/core/addons/kuberocketci-rbac/README.md
  clusters/core/addons/kuberocketci-rbac/README.md.gotmpl
Labels: enhancement

#219 fix: Add annatation to grafana ingress for iframe(#213)
  clusters/core/addons/prometheus-operator/README.md
  clusters/core/addons/prometheus-operator/values.yaml
Labels: enhancement

#220 fix: Align defectdojo oidc values(#213)
  clusters/core/addons/defectdojo/templates/oidc/keycloak-client-defectdojo.yaml
  clusters/core/addons/kuberocketci-rbac/README.md
Labels: bug

#222 chore: Implement Karma dashboard (#221)
  README.md
  clusters/core/addons/karma-dashboard/Chart.yaml
  clusters/core/addons/karma-dashboard/README.md
  clusters/core/addons/karma-dashboard/values.yaml
  clusters/core/apps/README.md
  clusters/core/apps/templates/karma-dashboard.yaml
  clusters/core/apps/values.yaml
Labels: enhancement
